from enum import Enum


class EventType(str, Enum):
    ORDER_CREATED = "ORDER_CREATED"
    PAYMENT_CAPTURED = "PAYMENT_CAPTURED"
    REFUND_CREATED = "REFUND_CREATED"
    FEE_APPLIED = "FEE_APPLIED"
    ADJUSTMENT_APPLIED = "ADJUSTMENT_APPLIED"
    SETTLEMENT_CREATED = "SETTLEMENT_CREATED"
    SETTLEMENT_PROCESSED = "SETTLEMENT_PROCESSED"
    BANK_CREDIT = "BANK_CREDIT"


class RecordSource(str, Enum):
    ORDER = "ORDER"
    PAYMENT = "PAYMENT"
    REFUND = "REFUND"
    FEE = "FEE"
    ADJUSTMENT = "ADJUSTMENT"
    SETTLEMENT = "SETTLEMENT"
    BANK = "BANK"

class ScenarioType(str, Enum):
    NORMAL_SETTLEMENT = "NORMAL_SETTLEMENT"
    PARTIAL_REFUND = "PARTIAL_REFUND"
    SPLIT_SETTLEMENT = "SPLIT_SETTLEMENT"